kind: ConfigMap
apiVersion: v1
metadata:
  name: alertmanager
  namespace: monitoring
data:
  config.yml: |-
    global:
       smtp_smarthost: 'smtp.126.com:25'
       smtp_from: 'xxxxx@126.com'
       smtp_auth_username: 'xxxx@126.com'
       smtp_auth_password: 'xxxxxxx'
       smtp_require_tls: false
                                
    route:
      group_by: ['instance']
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 7m
      receiver: email
      routes:
      - match:
          severity: critical
          receiver: email
      - match_re:
          severity: ^(warning|critical)$
          receiver: support_team
    
    receivers:
    - name: 'email'
      email_configs:
      - to: 'xxxxxx@qq.com'
    - name: 'support_team'
      email_configs:
      - to: 'xxxxxx@qq.com'
    - name: 'pager'
      email_configs:
      - to: 'alert-pager@example.com'
