apiVersion: v1
kind: Pod
metadata:
  name: vol-glusterfs-pod
  labels:
    app: redis
spec:
  containers:
  - name: redis
    image: redis:alpine
    ports:
    - containerPort: 6379
      name: redisport
    volumeMounts:
    - mountPath: /data
      name: redisdata
  volumes:
    - name: redisdata
      glusterfs:
        endpoints: glusterfs-endpoints         #Endpoints资源的名称，此资源需要实现存在，用于提供Gluster集群的步伐节点信息，必选字段
        path: kube-redis                       #用到的GlusterFS机器的卷路径，必选字段
        readOnly: false                        #是否为只读卷
